// <auto-generated />
using System;
using HandoffApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HandoffApi.Migrations
{
    [DbContext(typeof(HandoffDbContext))]
    [Migration("20260723193444_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HandoffApi.Models.ActionItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Completed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HandoffId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HandoffId");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("HandoffApi.Models.Clinician", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Clinicians");
                });

            modelBuilder.Entity("HandoffApi.Models.Contingency", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HandoffId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IfCondition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ThenAction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HandoffId");

                    b.ToTable("Contingencies");
                });

            modelBuilder.Entity("HandoffApi.Models.Handoff", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("ActionListReviewed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodeStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("IncomingClinician")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("NoKnownDrugAllergies")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OutgoingClinician")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Severity")
                        .HasColumnType("longtext");

                    b.Property<string>("ShiftLabel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Synthesis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("Handoffs");
                });

            modelBuilder.Entity("HandoffApi.Models.Patient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("AdmittedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("AgeYears")
                        .HasColumnType("int");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mrn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HandoffApi.Models.PendingStudy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FollowUpOwner")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HandoffId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Study")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HandoffId");

                    b.ToTable("PendingStudies");
                });

            modelBuilder.Entity("HandoffApi.Models.ActionItem", b =>
                {
                    b.HasOne("HandoffApi.Models.Handoff", "Handoff")
                        .WithMany("Actions")
                        .HasForeignKey("HandoffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Handoff");
                });

            modelBuilder.Entity("HandoffApi.Models.Contingency", b =>
                {
                    b.HasOne("HandoffApi.Models.Handoff", "Handoff")
                        .WithMany("Contingencies")
                        .HasForeignKey("HandoffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Handoff");
                });

            modelBuilder.Entity("HandoffApi.Models.Handoff", b =>
                {
                    b.HasOne("HandoffApi.Models.Patient", "Patient")
                        .WithOne("Handoff")
                        .HasForeignKey("HandoffApi.Models.Handoff", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HandoffApi.Models.PendingStudy", b =>
                {
                    b.HasOne("HandoffApi.Models.Handoff", "Handoff")
                        .WithMany("PendingStudies")
                        .HasForeignKey("HandoffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Handoff");
                });

            modelBuilder.Entity("HandoffApi.Models.Handoff", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Contingencies");

                    b.Navigation("PendingStudies");
                });

            modelBuilder.Entity("HandoffApi.Models.Patient", b =>
                {
                    b.Navigation("Handoff");
                });
#pragma warning restore 612, 618
        }
    }
}
